version: '2.1'

services:
  ai:
    build: .
    image: ai
    container_name: ai
    volumes:
      - "data_work:/home/ubuntu/work"
    #restart: always
    ports:
      - "22:22"
      - "5901:5901"
    network_mode: "host"

volumes:
  data_work:
