version: '2.1'

services:
  ai:
    build: .
    image: ai
    container_name: ai
    volumes:
      - "data_work:/home/ubuntu/work"
      - "/home/demers/share:/home/ubuntu/share"
    #restart: always
    ports:
      - "22:22"
    network_mode: "host"

volumes:
  data_work:
